# Write a Python program using NumPy to perform the following tasks on a given array:
1. Create a NumPy array with the following values: [1, 2, 3, 4, 5].
2. Print the shape of the array using the .shape attribute.
3. Reshape the array into a 2D array with 2 rows and 3 columns.
4. Print the shape of the new array.
5. Create a second NumPy array with the following values: [6, 7, 8, 9, 10].
6. Concatenate the two arrays together horizontally.
7. Print the resulting array.
8. Compute the resulting array's mean, median, and standard deviation.

**1. Create a NumPy array with the following values: [1, 2, 3, 4, 5].**

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


**2. Print the shape of the array using the .shape attribute.**

In [2]:
print(arr1.shape)

(5,)


**3. Reshape the array into a 2D array with 2 rows and 3 columns.**

In [8]:
arr2 = arr1.reshape(2, 3)
print(arr2)


[[1 2 3]
 [4 5 6]]


**4. Print the shape of the new array.**

In [23]:
print(arr2.shape)

(2, 3)


**5. Create a second NumPy array with the following values: [6, 7, 8, 9, 10].**

In [24]:
arr3 = np.array([6, 7, 8, 9, 10])

**6. Concatenate the two arrays together horizontally.**



In [30]:
arr4 = np.concatenate((arr2_reshaped, arr3_reshaped), axis=1)
print(arr4)

[[ 1  2  3  4  5  6  6  7  8  9 10]]


**7. Print the resulting array.**

In [31]:
print(arr4)

[[ 1  2  3  4  5  6  6  7  8  9 10]]


**8. Compute the resulting array's mean, median, and standard deviation.**

In [32]:
print("Mean: ", np.mean(arr4))
print("Median: ", np.median(arr4))
print("Standard Deviation: ", np.std(arr4))


Mean:  5.545454545454546
Median:  6.0
Standard Deviation:  2.74238238709061


# **Complete code**

In [44]:

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6])
print("Array 1 :",arr1)
print("Shape of arr1:", arr1.shape)

arr2 = arr1.reshape(2, 3)
print("Shape of arr2:", arr2.shape)
print("Array 2 :",arr2)

arr3 = np.array([6, 7, 8, 9, 10])
print("Array 3 :",arr3)

arr4 = np.concatenate((arr2_reshaped, arr3_reshaped), axis=1)
print("Concatenated array:", arr4)

print("Mean:", np.mean(arr4))
print("Median:", np.median(arr4))
print("Standard deviation:", np.std(arr4))


Array 1 : [1 2 3 4 5 6]
Shape of arr1: (6,)
Shape of arr2: (2, 3)
Array 2 : [[1 2 3]
 [4 5 6]]
Array 3 : [ 6  7  8  9 10]
Concatenated array: [[ 1  2  3  4  5  6  6  7  8  9 10]]
Mean: 5.545454545454546
Median: 6.0
Standard deviation: 2.74238238709061


AKULA ZAHEER SHA 

---


a.zaheersha@gmail.com

---


9494333702